# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: [file]
        files: \.(py|pyi)$

-   repo: https://github.com/sqlalchemyorg/zimports
    rev: 0.3.0
    hooks:
    -   id: zimports
        types: [file]
        files: \.(py|pyi)$

-   repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        types: [file]
        files: \.(py|pyi)$
        additional_dependencies:
          - flake8-import-order
          - flake8-pyi



